version: "3.3"

services:
  db:
    image: mysql:latest
    container_name: mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
    networks:
      - default

  php:
    container_name: php
    build: .
    ports: 
      - "8000:80"
    volumes:
      - ./..:/var/www/html
      - ./conf/php.ini:/usr/local/etc/php/php.ini
      - ./conf/apache2.conf:/etc/apache2/apache2.conf
      - ./conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    links:
      - db
    networks:
      - default

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      UPLOAD_LIMIT: 300M
    depends_on:
      - db
    networks:
      - default

networks:
  default:

volumes:
  persistent:
